theme: jekyll-theme-cayman
title: IoT-Router Convention
github:
  is_project_page: true
description: An agreement between interested parties covering positions, definitions and specifications for multiple Smart Living Applications und Internet Access on a single box.
